### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by rezemoe** [clevernt/MeshingCogs#1]
https://github.com/clevernt/MeshingCogs/blob/5c05f8fde644637608a8f51366290c9d4be38271/bot.py#L15

you know you can read the file names and load using those instead of manually typing each one

**Comment by rezemoe** [comment]
thank me later you know my paypal

**Comment by clevernt** [comment]
Not interested.

**Comment by rezemoe** [comment]
![image](https://c.tenor.com/-oKoLWm3RDMAAAAC/tenor.gif)
